[tool.poetry]
name = "plannerbenchmark"
version = "0.1.0"
description = "Benchmark suite for local planner in dynamic environment."
authors = ["Max Spahn <m.spahn@tudelft.nl>"]

[tool.poetry.dependencies]
python = "^3.6,<3.11"
forwardkinematics = {git = "https://git@github.com/maxspahn/forwardKinematics.git", rev = "main"}
planarenvs = {git = "https://git@github.com/maxspahn/gym_envs_planar.git", rev = "master"}
urdfenvs = {git = "https://git@github.com/maxspahn/gym_envs_urdf.git", rev = "master"}
robotmpcs = {git = "https://git@github.com/maxspahn/robot_mpcs.git", rev = "main", optional = true}
motion-planning-scenes= {git = "https://git@github.com/maxspahn/motion_planning_scenes.git", rev = "main"}
fabrics = {path = "../../../../code/fabrics"}

[tool.poetry.extras]
fabric = ['fabrics']
mpc = ['robotmpcs']

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
